version: "3.1"

services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: greenlight
      POSTGRES_USER: greenlight
      POSTGRES_PASSWORD: greenlight

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
# https://www.geeksforgeeks.org/postgresql-psql-commands/

# docker exec -it postgres psql -d greenlight -U greenlight

# CREATE ROLE greenlight WITH LOGIN PASSWORD 'pa55word';
# CREATE EXTENSION IF NOT EXISTS citext;

# Optimizing Postgres https://www.enterprisedb.com/postgres-tutorials/how-tune-postgresql-memory
# And https://pgtune.leopard.in.ua/
# SHOW config_file;

# export GREENLIGHT_DB_DSN=postgres://greenlight:greenlight@localhost/greenlight?sslmode=disable
# migrate -path=./migrations -database=$GREENLIGHT_DB_DSN up
# migrate -path=./migrations -database=$GREENLIGHT_DB_DSN version
# migrate -path=./migrations -database=$GREENLIGHT_DB_DSN goto 1
# migrate -path=./migrations -database =$GREENLIGHT_DB_DSN down
# migrate -path=./migrations -database =$GREENLIGHT_DB_DSN down 1
# migrate -path=./migrations -database=$EXAMPLE_DSN force 1